In [2]:
import pandas as pd
import numpy as np

In [19]:
import pandas as pd
import os

folder_path = r"C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data"

files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

dataframes = []

for file in files:
    path = os.path.join(folder_path, file)
    df = pd.read_csv(path, encoding='latin1')  
    dataframes.append(df)


# Merge all DataFrames into a single DataFrame
merged_df = pd.concat(dataframes, ignore_index=True)

# Display the merged DataFrame
merged_df

,property_id,type,activation_date,bathroom,floor,total_floor,furnishing,gym,latitude,longitude,...,property_age,property_size,swimming_pool,pin_code,rent,deposit,building_type,location,ÿþ,property_id/type/activation_date/bathroom/floor/total_floor/furnishing/gym/latitude/longitude/lease_type/lift/locality/parking/property_age/property_size/swimming_pool/pin_code/rent/deposit/building_type
0,ff8080814a078fd2014a15c813ff0b03,BHK3,20-02-2017 09:24,3.0,2.0,6.0,SEMI_FURNISHED,1,12.872456,77.617578,...,2.0,2000.0,0,560068.0,22000.0,150000.0,AP,NaN,NaN,NaN
1,ff8081814c2dea94014c50865ea35904,BHK2,11-03-2017 16:12,2.0,0.0,2.0,SEMI_FURNISHED,0,12.876009,77.617934,...,5.0,1250.0,0,560076.0,12500.0,125000.0,IF,NaN,NaN,NaN
2,ff8081814cff7251014d04e2cc7018fd,BHK2,18-03-2017 14:26,2.0,2.0,19.0,SEMI_FURNISHED,1,12.875923,77.617946,...,2.0,1279.0,1,560068.0,17500.0,175000.0,AP,NaN,NaN,NaN
3,ff8081814eb65997014ebbaa22f11869,BHK2,28-03-2017 11:09,2.0,3.0,5.0,SEMI_FURNISHED,1,12.859438,77.614948,...,1.0,1200.0,0,560076.0,15000.0,100000.0,AP,NaN,NaN,NaN
4,ff8081814fa8748d014fabcabea10bb6,BHK3,14-02-2017 17:07,2.0,1.0,3.0,SEMI_FURNISHED,0,12.875697,77.617187,...,1.0,1550.0,0,560076.0,18000.0,100000.0,AP,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14527,ff8081815b15c304015b18b33e467d05,BHK3,29-03-2017 12:30,3.0,6.0,7.0,SEMI_FURNISHED,1,13.114465,77.578528,...,6.0,1610.0,0,560064.0,20000.0,200000.0,AP,NaN,NaN,NaN
14528,ff8081815b15c304015b18f78f4e2503,BHK2,29-03-2017 13:18,2.0,3.0,3.0,SEMI_FURNISHED,1,13.122433,77.582765,...,4.0,1155.0,1,560064.0,15000.0,150000.0,AP,NaN,NaN,NaN
14529,ff8081815b15c304015b1a4c67134ce4,BHK3,30-03-2017 14:10,1.0,1.0,14.0,SEMI_FURNISHED,1,13.097357,77.570412,...,5.0,1680.0,1,560065.0,8500.0,60000.0,AP,NaN,NaN,NaN
14530,ff8081815b15c304015b1df97fb2695f,BHK3,30-03-2017 12:36,2.0,7.0,17.0,SEMI_FURNISHED,0,13.117724,77.577400,...,2.0,1326.0,0,560064.0,19000.0,150000.0,AP,NaN,NaN,NaN
14531,ff8081815b1e0e51015b1e3ef2b51346,BHK2,30-03-2017 15:23,2.0,0.0,0.0,SEMI_FURNISHED,0,13.103437,77.612229,...,0.0,1600.0,0,560064.0,11500.0,100000.0,IH,NaN,NaN,NaN

In [22]:
len(merged_df.columns.to_list())

24

In [10]:
csv_files

['Akshayanagar.csv',
 'Arekere.csv',
 'Banashankari.csv',
 'Basavanagudi.csv',
 'Basaveshwar Nagar.csv',
 'Begur.csv',
 'Bellandur.csv',
 'Bilekahalli.csv',
 'Bommanahalli.csv',
 'Brookefield.csv',
 'BTM 2nd Stage.csv',
 'BTM_Layout.csv',
 'Chikkalasandra.csv',
 'Doddanekundi.csv',
 'Ejipura.csv',
 'Electronic City.csv',
 'Electronics City Phase 1.csv',
 'Gottigere.csv',
 'HBR Layout.csv',
 'Hebbal.csv',
 'Hongasandra.csv',
 'Hoodi.csv',
 'Horamavu.csv',
 'Hosakerehalli.csv',
 'HSR_Layout.csv',
 'Hulimavu.csv',
 'Indiranagar.csv',
 'Jayanagar.csv',
 'JP Nagar.csv',
 'K.R Puram.csv',
 'Kadugodi.csv',
 'Kaggadasapura.csv',
 'Kalyan Nagar.csv',
 'Kammanahalli.csv',
 'Kasavanahalli.csv',
 'Kengeri Satellite Town.csv',
 'Kengeri.csv',
 'Konanakunte.csv',
 'Koramangala.csv',
 'Krishnarajapura.csv',
 'Kumaraswamy Layout.csv',
 'Lingarajapuram.csv',
 'Mahadevapura.csv',
 'Marathahalli.csv',
 'Mathikere.csv',
 'Munnekollal.csv',
 'Nagarbhavi.csv',
 'Padmanabhanagar.csv',
 'Raja Rajeshwari Nagar.csv',
 'Rajaji Nagar.csv',
 'Ramamurthy Nagar.csv',
 'RR Nagar.csv',
 'RT Nagar.csv',
 'Singasandra.csv',
 'Subramanyapura.csv',
 'Sunkadakatte.csv',
 'Thanisandra.csv',
 'Uttarahalli Hobli.csv',
 'Varthur.csv',
 'Vidyaranyapura.csv',
 'Vijaya Nagar.csv',
 'Whitefield.csv',
 'Yelahanka New Town.csv',
 'Yelahanka.csv']

In [15]:
df=pd.read_csv(r"C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Akshayanagar.csv")

In [16]:
df

,property_id,type,activation_date,bathroom,floor,total_floor,furnishing,gym,latitude,longitude,...,lift,locality,parking,property_age,property_size,swimming_pool,pin_code,rent,deposit,building_type
0,ff8080814a078fd2014a15c813ff0b03,BHK3,20-02-2017 09:24,3,2,6.0,SEMI_FURNISHED,1,12.872456,77.617578,...,1,Akshayanagar,BOTH,2,2000,0,560068.0,22000,150000,AP
1,ff8081814c2dea94014c50865ea35904,BHK2,11-03-2017 16:12,2,0,2.0,SEMI_FURNISHED,0,12.876009,77.617934,...,0,Akshayanagar,BOTH,5,1250,0,560076.0,12500,125000,IF
2,ff8081814cff7251014d04e2cc7018fd,BHK2,18-03-2017 14:26,2,2,19.0,SEMI_FURNISHED,1,12.875923,77.617946,...,1,Akshayanagar,BOTH,2,1279,1,560068.0,17500,175000,AP
3,ff8081814eb65997014ebbaa22f11869,BHK2,28-03-2017 11:09,2,3,5.0,SEMI_FURNISHED,1,12.859438,77.614948,...,1,Akshayanagar,BOTH,1,1200,0,560076.0,15000,100000,AP
4,ff8081814fa8748d014fabcabea10bb6,BHK3,14-02-2017 17:07,2,1,3.0,SEMI_FURNISHED,0,12.875697,77.617187,...,1,Akshayanagar,BOTH,1,1550,0,560076.0,18000,100000,AP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,ff8081815af60983015af6372321123c,BHK2,22-03-2017 19:25,2,1,10.0,SEMI_FURNISHED,1,12.875923,77.617914,...,1,Akshayanagar,BOTH,0,918,1,560068.0,18000,180000,AP
140,ff8081815b00b011015b03d8924e4761,BHK3,26-03-2017 08:43,2,4,19.0,SEMI_FURNISHED,0,12.875933,77.617893,...,1,Akshayanagar,BOTH,0,1425,0,560068.0,22000,200000,AP
141,ff8081815b05c610015b0935fd696894,BHK2,28-03-2017 12:12,2,7,19.0,SEMI_FURNISHED,1,12.876045,77.617910,...,1,Akshayanagar,FOUR_WHEELER,0,1319,1,560076.0,20000,170000,AP
142,ff8081815b0f1e48015b0f40f2380e38,BHK3,27-03-2017 19:49,2,4,18.0,SEMI_FURNISHED,0,12.876075,77.618423,...,1,Akshayanagar,BOTH,0,1200,0,560076.0,22000,220000,AP
143,ff8081815b106c7d015b194b18225ec6,BHK1,29-03-2017 15:34,1,1,3.0,SEMI_FURNISHED,0,12.876012,77.616082,...,0,Akshayanagar,TWO_WHEELER,1,425,0,560076.0,7500,60000,IF

In [14]:
# Read each CSV file into a separate DataFrame
for file in csv_files:
    path = folder_path + '\\'+file
    print(path)

C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Akshayanagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Arekere.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Banashankari.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Basavanagudi.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Basaveshwar Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Begur.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Bellandur.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Bilekahalli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Bommanahalli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Brookefield.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\BTM 2nd Stage.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\BTM_Layout.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Chikkalasandra.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Doddanekundi.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Ejipura.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Electronic City.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Electronics City Phase 1.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Gottigere.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\HBR Layout.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Hebbal.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Hongasandra.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Hoodi.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Horamavu.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Hosakerehalli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\HSR_Layout.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Hulimavu.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Indiranagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Jayanagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\JP Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\K.R Puram.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kadugodi.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kaggadasapura.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kalyan Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kammanahalli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kasavanahalli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kengeri Satellite Town.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kengeri.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Konanakunte.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Koramangala.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Krishnarajapura.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Kumaraswamy Layout.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Lingarajapuram.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Mahadevapura.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Marathahalli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Mathikere.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Munnekollal.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Nagarbhavi.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Padmanabhanagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Raja Rajeshwari Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Rajaji Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Ramamurthy Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\RR Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\RT Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Singasandra.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Subramanyapura.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Sunkadakatte.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Thanisandra.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Uttarahalli Hobli.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Varthur.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Vidyaranyapura.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Vijaya Nagar.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Whitefield.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Yelahanka New Town.csv
C:\Users\91852\Downloads\Property_data-20250109T062142Z-001\Property_data\Yelahanka.csv